[project]
name = "texttools-app"
version = "0.1.0"
description = "A simple API for TextTools"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]==0.133.0",
    "hamtaa-texttools>=2.8.0",
    "jinja2>=3.1.6",
    "pydantic-settings>=2.12.0",
]
